apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:      
      wasm:
        config: |
         {}
        image: webassemblyhub.io/christian-posta/filter-test:v0.2
        name: christian
        root_id: add_header_root_id
  proxyNames:
  - gateway-proxy
  useProxyProto: false